#Server
server:
  port: 8070

#DataBase
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_DB_USER}
    password: ${POSTGRES_DB_PASSWORD}
  flyway:
    url: ${POSTGRES_DB_URL}
    locations: classpath:db/migration
    user: ${POSTGRES_DB_USER}
    password: ${POSTGRES_DB_PASSWORD}
    validate-migration-naming: true

#OpenApi
springdoc:
  api-docs:
    groups:
      enabled: true
    path: /swagger-doc/v3/api-docs
  swagger-ui:
    path: /swagger-doc/swagger-ui.html

